name: 
parameters:
  - name: url
    displayName: 'Provide URL details'
    type: string
    default: 'null'
   
trigger:
  - master
pool: Ubuntu24-VM-Pool
pr: none

variables:
  - name: MAVEN_CACHE_FOLDER
    value: $(HOME)/.m2/repository
  - name: MAVEN_OPTS
    value: -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)
  - name: npm_config_cache 
    value: $(HOME)/.npm
  - name: JACOCO_CODECOVERAGE
    value: $(System.DefaultWorkingDirectory)/core/target/site/jacoco/jacoco.xml

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildJob
        displayName: Master Build Job
        pool:
         vmImage: ubuntu-latest
        steps:
         - checkout: self
           persistCredentials: true
           clean: true
           fetchDepth: 0 

         - script: |
             if [ "${{ parameters.url }}" = "null" ]; then
               echo "##vso[task.setvariable variable=setUrl]master_url"
             else
               echo "##vso[task.setvariable variable=setUrl]${{ parameters.url }}"
             fi
           displayName: 'Set URL Variable'
  # Set up maven repo cache
         - task: Cache@2
           displayName: Cache Maven local repo
           inputs:
             key: maven | "$(Agent.OS)" | **/pom.xml
             path: $(MAVEN_CACHE_FOLDER)
             restoreKeys: |
               maven | "$(Agent.OS)"
               maven
         - task: SonarQubePrepare@6
           inputs:
              SonarQube: 'my-cnx'
              scannerMode: 'Other'
              configMode: file
              extraProperties: |
                sonar.projectKey=testtt
                sonar.projectName=testtt
                sonar.language=java
                sonar.sourceEncoding=UTF-8
                sonar.test=core/src/test/**
                sonar.java.binaries=.
                sonar.coverage.jacoco.xmlReportPaths=$(JACOCO_CODECOVERAGE)
           enabled: true
  # Perform AEM maven build
         - task: Maven@4
           displayName: AEM Build
           inputs:
            goals: '-B package'
            publishJUnitResults: true
            mavenOpts: '-Xmx2048m $(MAVEN_OPTS)'
            sonarQubeRunAnalysis: true
         - task: SonarQubePublish@6
           inputs:
            pollingTimeoutSec: '300'
         - task: PublishCodeCoverageResults@2
           inputs:
             summaryFileLocation: '$(System.DefaultWorkingDirectory)/core/target/site/jacoco/jacoco.xml'
             failIfCoverageEmpty: true
