trigger:
- master

pool:
  name: Ubuntu24-VM-Pool

steps:
- script: |
    echo "Checking Maven version:"
    mvn -v
    echo "Checking Java version:"
    java -version
  displayName: 'Check Maven and Java Versions'
